import { MealAnalysis } from "./types";

/**
 * High-quality mock data for demo/development when Gemini API is unavailable.
 * Simulates a "Pizza + Coke" meal analysis.
 */
export const mockPizzaCokeAnalysis: MealAnalysis = {
  foods: [
    {
      name: "Pepperoni Pizza (2 slices)",
      emoji: "🍕",
      calories: 570,
      protein: 24,
      carbs: 62,
      fat: 24,
      fiber: 3,
      sugar: 8,
      sodium: 1280,
    },
    {
      name: "Cola (330ml)",
      emoji: "🥤",
      calories: 140,
      protein: 0,
      carbs: 39,
      fat: 0,
      fiber: 0,
      sugar: 39,
      sodium: 45,
    },
  ],
  timeline: [
    { time: "+5 min", minutes: 5, effect: "Dopamine surge from flavor combination", intensity: 0.9, type: "positive" },
    { time: "+15 min", minutes: 15, effect: "Blood sugar spike begins", intensity: 0.7, type: "neutral" },
    { time: "+30 min", minutes: 30, effect: "Peak energy — sugar + carbs hit bloodstream", intensity: 0.85, type: "positive" },
    { time: "+60 min", minutes: 60, effect: "Insulin response kicks in, energy plateau", intensity: 0.5, type: "neutral" },
    { time: "+90 min", minutes: 90, effect: "Energy crash begins — sugar dip", intensity: 0.7, type: "negative" },
    { time: "+2 hrs", minutes: 120, effect: "Brain fog and decreased focus", intensity: 0.6, type: "negative" },
    { time: "+3 hrs", minutes: 180, effect: "Hunger returns despite high calorie intake", intensity: 0.5, type: "negative" },
    { time: "+4 hrs", minutes: 240, effect: "Energy stabilizes at below-baseline level", intensity: 0.4, type: "negative" },
  ],
  bodyEffects: [
    { organ: "brain", label: "Brain", status: "poor", color: "#ff4444", description: "Sugar crash will reduce focus and clarity within 90 minutes", intensity: 0.7 },
    { organ: "stomach", label: "Stomach", status: "moderate", color: "#ffaa00", description: "Heavy, slow digestion from cheese and refined carbs", intensity: 0.6 },
    { organ: "muscles", label: "Muscles", status: "moderate", color: "#ffaa00", description: "Some protein from cheese, but high sodium may cause bloating", intensity: 0.5 },
    { organ: "heart", label: "Heart", status: "poor", color: "#ff6644", description: "High sodium (1325mg) — elevated cardiovascular stress", intensity: 0.65 },
    { organ: "hydration", label: "Hydration", status: "poor", color: "#ff4444", description: "Cola is a diuretic — net hydration negative", intensity: 0.75 },
  ],
  energyCurve: [
    { minute: 0, energy: 50, focus: 60 },
    { minute: 10, energy: 55, focus: 58 },
    { minute: 20, energy: 70, focus: 55 },
    { minute: 30, energy: 85, focus: 50 },
    { minute: 45, energy: 80, focus: 48 },
    { minute: 60, energy: 65, focus: 42 },
    { minute: 75, energy: 50, focus: 38 },
    { minute: 90, energy: 35, focus: 30 },
    { minute: 105, energy: 30, focus: 28 },
    { minute: 120, energy: 28, focus: 32 },
    { minute: 150, energy: 32, focus: 35 },
    { minute: 180, energy: 38, focus: 40 },
    { minute: 210, energy: 40, focus: 42 },
    { minute: 240, energy: 42, focus: 45 },
    { minute: 300, energy: 45, focus: 48 },
    { minute: 360, energy: 48, focus: 50 },
  ],
  hydrationImpact: -25,
  satietyDuration: 120,
  overallScore: 32,
  aiInsight: "This meal delivers a rapid but short-lived energy boost. The combination of refined carbs from pizza dough and 39g of sugar from cola creates a pronounced blood sugar spike followed by a sharp crash around the 90-minute mark. Expect reduced mental clarity and an early return of hunger. The high sodium content (1,325mg — over half your daily limit) will promote water retention and may cause bloating.",
  moodPrediction: "Initial satisfaction and comfort, followed by sluggishness and difficulty concentrating. Not recommended before study sessions, important meetings, or physical activity.",
  swapSuggestion: {
    remove: "Cola (330ml)",
    replaceWith: "Sparkling water with lemon",
    benefit: "Eliminates 39g sugar, prevents crash, improves hydration",
    impactDelta: 18,
  },
  longTermEffect: "Daily consumption of this meal combination may lead to chronic energy instability, increased sugar cravings, progressive reduction in focus capacity, and elevated risk of metabolic stress. Over 6 months, expect potential weight gain of 4-7kg and decreased sleep quality due to blood sugar fluctuations.",
  foodDna: [
    { type: "carbs", label: "Carbs", percentage: 42, grams: 101, color: "#FFB800" },
    { type: "fat", label: "Fat", percentage: 20, grams: 24, color: "#FF6B6B" },
    { type: "protein", label: "Protein", percentage: 10, grams: 24, color: "#00FFD1" },
    { type: "sugar", label: "Sugar", percentage: 20, grams: 47, color: "#FF4488" },
    { type: "fiber", label: "Fiber", percentage: 1, grams: 3, color: "#88FF88" },
    { type: "sodium", label: "Sodium", percentage: 7, grams: 1.3, color: "#8888FF" },
  ],
  totalCalories: 710,
};

/**
 * Mock data for a healthy meal comparison.
 */
export const mockHealthyMealAnalysis: MealAnalysis = {
  foods: [
    {
      name: "Grilled Chicken Salad",
      emoji: "🥗",
      calories: 350,
      protein: 35,
      carbs: 20,
      fat: 14,
      fiber: 8,
      sugar: 6,
      sodium: 420,
    },
    {
      name: "Green Tea",
      emoji: "🍵",
      calories: 5,
      protein: 0,
      carbs: 1,
      fat: 0,
      fiber: 0,
      sugar: 0,
      sodium: 5,
    },
  ],
  timeline: [
    { time: "+5 min", minutes: 5, effect: "Gentle satisfaction from balanced flavors", intensity: 0.6, type: "positive" },
    { time: "+15 min", minutes: 15, effect: "Steady nutrient absorption begins", intensity: 0.5, type: "positive" },
    { time: "+30 min", minutes: 30, effect: "Sustained energy from protein + complex carbs", intensity: 0.7, type: "positive" },
    { time: "+60 min", minutes: 60, effect: "Mental clarity enhanced by green tea L-theanine", intensity: 0.8, type: "positive" },
    { time: "+90 min", minutes: 90, effect: "Stable energy — no crash detected", intensity: 0.7, type: "positive" },
    { time: "+2 hrs", minutes: 120, effect: "Continued focus and steady energy", intensity: 0.65, type: "positive" },
    { time: "+3 hrs", minutes: 180, effect: "Gradual, natural hunger return", intensity: 0.4, type: "neutral" },
    { time: "+4 hrs", minutes: 240, effect: "Energy remains above baseline", intensity: 0.3, type: "positive" },
  ],
  bodyEffects: [
    { organ: "brain", label: "Brain", status: "excellent", color: "#00FFD1", description: "L-theanine + protein promote sustained focus and clarity", intensity: 0.9 },
    { organ: "stomach", label: "Stomach", status: "good", color: "#44ff88", description: "High fiber content supports smooth digestion", intensity: 0.7 },
    { organ: "muscles", label: "Muscles", status: "excellent", color: "#00FFD1", description: "35g complete protein — excellent for recovery", intensity: 0.85 },
    { organ: "heart", label: "Heart", status: "excellent", color: "#00FFD1", description: "Low sodium, healthy fats — heart-friendly meal", intensity: 0.9 },
    { organ: "hydration", label: "Hydration", status: "good", color: "#44ff88", description: "Green tea provides gentle hydration with antioxidants", intensity: 0.7 },
  ],
  energyCurve: [
    { minute: 0, energy: 50, focus: 60 },
    { minute: 10, energy: 55, focus: 62 },
    { minute: 20, energy: 60, focus: 65 },
    { minute: 30, energy: 68, focus: 70 },
    { minute: 45, energy: 72, focus: 75 },
    { minute: 60, energy: 74, focus: 78 },
    { minute: 75, energy: 72, focus: 76 },
    { minute: 90, energy: 70, focus: 74 },
    { minute: 105, energy: 68, focus: 72 },
    { minute: 120, energy: 65, focus: 70 },
    { minute: 150, energy: 60, focus: 65 },
    { minute: 180, energy: 55, focus: 60 },
    { minute: 210, energy: 52, focus: 56 },
    { minute: 240, energy: 50, focus: 54 },
    { minute: 300, energy: 48, focus: 52 },
    { minute: 360, energy: 48, focus: 50 },
  ],
  hydrationImpact: 10,
  satietyDuration: 210,
  overallScore: 87,
  aiInsight: "This is an excellent balanced meal. The grilled chicken provides high-quality protein for sustained energy, while the salad greens deliver fiber and micronutrients. Green tea adds L-theanine, which promotes calm focus without the jitters of coffee. Expect steady energy for 3–4 hours with no crash.",
  moodPrediction: "Calm alertness and sustained mental clarity. Ideal before study sessions, creative work, or moderate exercise.",
  swapSuggestion: {
    remove: "Standard dressing",
    replaceWith: "Olive oil & lemon dressing",
    benefit: "Adds healthy omega fats, reduces processed ingredients",
    impactDelta: 5,
  },
  longTermEffect: "Regular consumption of balanced meals like this supports stable energy throughout the day, improved sleep quality, gradual body composition improvement, and enhanced cognitive performance. Over 6 months, expect increased mental endurance and reduced sugar cravings.",
  foodDna: [
    { type: "protein", label: "Protein", percentage: 36, grams: 35, color: "#00FFD1" },
    { type: "carbs", label: "Carbs", percentage: 22, grams: 21, color: "#FFB800" },
    { type: "fat", label: "Fat", percentage: 14, grams: 14, color: "#FF6B6B" },
    { type: "fiber", label: "Fiber", percentage: 8, grams: 8, color: "#88FF88" },
    { type: "sugar", label: "Sugar", percentage: 6, grams: 6, color: "#FF4488" },
    { type: "sodium", label: "Sodium", percentage: 14, grams: 0.4, color: "#8888FF" },
  ],
  totalCalories: 355,
};
